### ISSUE TITLE
test is not a function

### ISSUE THREAD

**Issue by AllaSydoriak-asd** [hyperform/hyperform#125]
Hi!

Recently I have noticed that some input fields started not working with hyperform. I can't type anything in there. And I permenantly get this error `Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value).test is not a function` which is raised on the 2nd line of hyperform.min.js. 

Firsty I thought that this is connected to "pattern" property, but even if I remove it, the form still can't submit and all error messages that I see is described above.

Do you have any thoughts what the reason can be?

Thank you.

**Comment by Boldewyn** [comment]
Hm, this is strange. Could you do me a favor and do two things:

1. Try using `hyperform.js` without minification (i.e., not the one with `.min` in the file name). This will provide us with a more granular line number to look for the problem.
2. Can you share the HTML snippet (basically just the `<input>`/`<textarea>` element)  where the problem appears?

Thank you!

**Comment by AllaSydoriak-asd** [comment]
1. It shows error in this line `hyperform.js:1279`
2. here is one of examples:
`<input 
      type="tel" 
      name="cvv" 
      data-name="cvv" 
      class="hf-validated hf-invalid user-error" 
      id="cvv" 
      pattern="[0-9]{3,4}" 
      placeholder="Security Code" 
      title="Please enter 3 digits for your CVV, or 4 digits for American Express" 
      value="" 
      required="" 
      aria-invalid="true"
 >`

**Comment by Boldewyn** [comment]
This was caused by a misplaced parenthesis. Thank you very much for the report! The fix is now in the repository.

As a side note: I suggest to use official releases. The error was introduced by problematic code last week, but there are also other issues currently worked at, and some parts of the code do not work yet as intended between releases. (In this concrete case: The stepUp and stepDown functions are currently worked at and do not yet work again.)

**Comment by AllaSydoriak-asd** [comment]
Thank you for a quick fix! 

Just a question. Should this changes apply now and if yes, is this url `<script src="https://cdn.rawgit.com/hyperform/hyperform/master/dist/hyperform.js"/>` is correct? becuase issue is still reproducible.

**Comment by Boldewyn** [comment]
Yes, the content behind that URL should update eventually. I assume it is cached for some time.

An alternative URL for a stable version would be, e.g., https://unpkg.com/hyperform@0.12.1/dist/hyperform.min.js . There the problem is not present, too.
