### ISSUE TITLE
Using snake_case instead of camelCase

### ISSUE THREAD

**Issue by Avol-V** [hyperform/hyperform#15]
It's not native for JavaScript to use snake_case at all, especially when it mixed with regular JS methods, as in your examples.

**Comment by Boldewyn** [comment]
Thanks for the feedback! The idea was to use snake case for all non-DOM APIs to distinguish them. But, yes, you have a point here. I have no strong feelings either way.

If you want, you could provide a pull request, and I'd merge it for a new minor version.

**Comment by Boldewyn** [comment]
Fixed in 513148cd1bd0f14c8241e8cd4c6055f7507877f7.
