### ISSUE TITLE
FYI: HTML 5.2 API additions and CSS level 4 selectors

### ISSUE THREAD

**Issue by kevinSuttle** [hyperform/hyperform#18]
## HTML 5.2

http://developer.telerik.com/featured/welcome-to-html-5-2/#toc_4

> <ul>
> <li>The <code>month</code> and <code>week</code> values of the <code>type</code> attribute of the <code>&lt;input&gt;</code> element. As their name suggest, they define controls for setting the element's value to a string representing a month and a week.</li>
> <li>The <code>forceSpellcheck()</code> method has been added to the <code>HTMLElement</code> interface and allows you, as a developer, to force the user agent to perform a spelling and grammar check on the element it is invoked on, even if the user has not focused it. An example of usage would be <code>inputElement.forceSpellcheck()</code>. Unfortunately, no browsers support it yet.</li>
> <li>The <code>allowfullscreen</code> attribute is a Boolean attribute for the <code>iframe</code> element and it specifies that the <code>iframe</code> is allowed to be in full screen mode when calling the <code>requestFullScreen()</code> method. If this isn't set, the element can't be in full screen mode.</li>
> <li>The <code>reportValidity()</code> method, when invoked, forces user agent to validate the constraints of the <code>&lt;form&gt;</code> element. Some examples are to check if a <code>required</code> element has not been filled or if a field respects its <code>pattern</code> attribute. It returns <code>true</code> if the constraint validation returns a positive result or <code>false</code> otherwise. This method is currently supported by Chrome and Opera.</li>
> </ul>
## CSS level 4 user pseudos

https://drafts.csswg.org/selectors/#user-pseudos

> <p>The <dfn class="dfn-paneled css" data-dfn-type="selector" data-export="" id="user-error-pseudo">:user-invalid</dfn> pseudo-class
>     represents an element with incorrect input, but only <em>after</em> the user has significantly interacted with it.
>     The <span class="css">:user-error</span> pseudo-class
>     must match an <a class="css" data-link-type="maybe" href="#invalid-pseudo" id="ref-for-invalid-pseudo-4">:invalid</a>, <a class="css" data-link-type="maybe" href="#out-of-range-pseudo" id="ref-for-out-of-range-pseudo-4">:out-of-range</a>, or blank-but-<a class="css" data-link-type="maybe" href="#required-pseudo" id="ref-for-required-pseudo-2">:required</a> elements
>     between the time the user has attempted to submit the form
>     and before the user has interacted again with the form element.
>     User-agents may allow it to match such elements at other times,
>     as would be appropriate for highlighting an error to the user.
>     For example, a UA may choose to have <span class="css">:user-error</span> match
>     an <a class="css" data-link-type="maybe" href="#invalid-pseudo" id="ref-for-invalid-pseudo-5">:invalid</a> element once the user has typed some text into it
>     and changed the focus to another element,
>     and to stop matching only after the user has successfully corrected the input.</p>

Not sure if this is `user-invalid` or `user-error`.
https://www.w3.org/TR/2013/WD-selectors4-20130502/#user-pseudos

**Comment by Boldewyn** [comment]
Thanks! That's useful, yes.

* [x] `month` and `week` are already supported: e.g., [this method](https://github.com/hyperform/hyperform/blob/master/src/tools/string_to_date.js) is used in `element.valueAsDate`.
* [ ] `forceSpellcheck()`. Hm, I need to look around, if there is an API to trigger spell checks in browsers.
* [x] `allowfullscreen` seems to be off-topic, since we do not target `iframe`s
* [x] `reportValidity()` is already supported. You can use it in either way:
    ```js
    element.reportValidity(); // via the polyfill, or...
    hyperform.reportValidity(element); // ...via the library
   ```
* [ ] `:user-invalid` this is a great selector! I'll try to wrap my head around how to bring that to Hyperform. For the time being, you can simulate it with `.hf-validated.hf-invalid` or set your own classes with [`hyperform({classes:{...}})`](https://hyperform.js.org/docs/usage.html#configuration).

**Comment by kevinSuttle** [comment]
I managed this with PostCSS: http://astexplorer.net/#/XT995gAElO/2

**Comment by Boldewyn** [comment]
Thanks! Would it be OK, if I'd take the code as base of a MIT licensed PostCSS plugin that handles pseudo-class :arrow_forward: Hyperform-class translations?

**Comment by kevinSuttle** [comment]
Absolutely. Happy to contribute.

**Comment by Boldewyn** [comment]
New CSS validators supported via PostCSS-Plugin: https://github.com/hyperform/postcss-hyperform

Thanks again for the idea!

**Comment by Boldewyn** [comment]
Re: `forceSpellcheck()`: http://stackoverflow.com/a/5221809/113195 Hm.

**Comment by Boldewyn** [comment]
`forceSpellcheck` being the last on the list: I don't think it's important enough for Hyperform core to justify lots of code for it. But when #14 is addressed and fully documented, there's nothing to hinder writing a Hyperform plugin to do spell checking with the above mention method from StackOverflow.
