### ISSUE TITLE
Add ability to disable logging 

### ISSUE THREAD

**Issue by pplewa** [hyperform/hyperform#21]
When the property fails to install it outputs logs that are very noisy in test environments like PhantomJS.

**Comment by Boldewyn** [comment]
Yeah, that is a rather fresh new feature, that I had to implement after crashing my head at the desk for a day, why it works in Safari 10, but not Safari 9.

PhantomJS unfortunately inherits this via its WebKit and JavaScriptCore version. I can totally see, why that is a problem for you.

I've not completely made up my mind how to fix this. Maybe a `quiet` parameter or a `debug` param (other way round than `quiet`) for the `hyperform` constructor? Would that fit your needs?

```js
const wrapper = hyperform({
    debug: false,
    // or
    quiet: true,
});
```

**Comment by pplewa** [comment]
That would work. Thanks for looking at this, haven't gotten around to look at the code and create PR myself.

**Comment by Boldewyn** [comment]
Sorry for the delay! Version 0.8.10 now features a `debug` config option to switch console messages on/off. Default is `false`, so you should be fine with just upgrading.
