### ISSUE TITLE
Will not validate other date formats than YYYY-MM-DD

### ISSUE THREAD

**Issue by sbibauw** [hyperform/hyperform#30]
On an `<input type="date">` Hyperform requires a strict `YYYY-MM-DD` format, while HTML5 accepts to set different patterns (a specific pattern can be set with the `pattern=""` attribute, but Hyperform seems to ignore this attribute).
From my understanding of Hyperform.js code, I suppose the problem is the `if` conditions in `function string_to_date()` (lines 876-928). A solution would be to accept various patterns:

- YYYY-MM-DD
- YYYY.MM.DD
- DD-MM-YYYY
- DD/MM/YYYY
- DD.MM.YYYY
- MM-DD-YYYY
- etc.

**Comment by Boldewyn** [comment]
Thanks for the report! Unfortunately, the spec is unambiguous with regard to the `date` type (both specs, that is, the [WHATWG](https://html.spec.whatwg.org/multipage/forms.html#date-state-(type=date)) and the [W3C](https://www.w3.org/TR/html5/forms.html#date-state-(type=date))). The `pattern` attribute is not allowed at all on such an `<input>`, and the value _must_ be an ISO datetime string. Short mind game: What format does this date represent?

    <input type=date pattern="[0-9]{2}.[0-9]{2}.[0-9]{2}">

Is it DD.MM.YY? YY.MM.DD? MM.DD.YY? The browser is supposed to send an unambiguous ISO datetime string back to the server. What should it do here?

Of course, that's mostly not acceptable for end users. So, what to do? Hide the original input and replace it with a widget of your liking. If you use jQuery UI, this is how you could do it with their datetime picker:

```js
var $original = $('your original input element');
var $widget = $('<input>', {
      type: 'text',
      value: $.datepicker.formatDate('dd.mm.yy', $original[0].valueAsDate),
});

$original
  .hide()
  .after(
    $widget
      .datepicker({
        altField: $original,
        altFormat: 'yy-mm-dd',
      })
      .on('change', function() {
        if (! $widget.val()) { $original.val(''); }
      })
    );
```

**Comment by sbibauw** [comment]
Thank you very much for your detailed answer. Sorry about my mistake regarding `date` type input and `pattern` attribute. You are absolutely right. :)
