### ISSUE TITLE
hyperform doesn't instantiating at form element in IE <=10

### ISSUE THREAD

**Issue by platov** [hyperform/hyperform#35]
In IE <= 10 when i instantiate hyperform at some form element `hyperform(myForm)` - i getting exception `Invalid operand to 'instanceof': Function expected`.

The problem is that hyperforms Wrapper function checking condition:
```javascript
if (form === window || form instanceof window.HTMLDocument) {
    ...
}
```
`instanceof window.HTMLDocument` fails because of `HTMLDocument` is undefined

**Comment by Boldewyn** [comment]
Minimal test case:

```html
<script src="https://unpkg.com/weakmap"></script>
<script src="https://unpkg.com/hyperform@0.8.14/dist/hyperform.js"></script>
<script>
/* anything but window as first argument */
hyperform(document);
</script>
```
