### ISSUE TITLE
Min Length warning message using max length number

### ISSUE THREAD

**Issue by david-witt-fluid** [hyperform/hyperform#45]
[Codepen to replicate](http://codepen.io/david-witt-fluid/pen/qrOYzv)

Enter a value less than 10 characters and hit submit.

"Please lengthen this text to [number] characters" is pulling the number from maxlength or displaying null if there is no maxlength defined.

**Comment by Boldewyn** [comment]
Good catch, thank you!

**Comment by david-witt-fluid** [comment]
Thanks!

Works like a charm.
