### ISSUE TITLE
Connect error messages via `aria-describedby`

### ISSUE THREAD

**Issue by Boldewyn** [hyperform/hyperform#5]

**Comment by Boldewyn** [comment]
Apparently ARIA 1.1 introduced [`aria-errormessage`](http://rawgit.com/w3c/aria/master/aria/aria.html#aria-errormessage). Seems more appropriate, and we don't have to deal with pre-existing labels.

**Comment by Boldewyn** [comment]
Fixed in d3dab6e004174d742ad9f5f35d853376e33ad75b

**Comment by Nettsentrisk** [comment]
I would probably use both aria-describedby and aria-errormessage until the latter is more widely implemented and supported in user agents and screen readers.

**Comment by Boldewyn** [comment]
Good point. Disadvantage is, that we'd have to make sure, an existing `aria-describedby` is not clobbered. That was the main reason I jumped on the `aria-errormessage` bandwagon. But all in all you're right, it would be better to set both attributes for now.
