### ISSUE TITLE
Global Custom Messages

### ISSUE THREAD

**Issue by SlimerDude** [hyperform/hyperform#71]
I would like to change the default global message for `tooShort` because at 91 characters, ironically this message is too long to fit in my msg div!

I could set the msg on individual elements, but that involves capturing whenever a form is dynamically created, checking for `minlength` attributes and setting the msg. It would be much easier if I could just set the msg once when I initialise hyperform.

Only the `tooShort` message is not defined in `localization.js` so I can not set a new default `en` translation for it. Instead the message is hardcoded in `validity_state_checkers.js` as are many other default messages.

Could all default messages be moved to `localization.js` so all msgs may be overridden in the one place?

**Comment by Boldewyn** [comment]
Default messages, that are not in `localization.js` are printed as-is. In this case, looking at
https://github.com/hyperform/hyperform/blob/master/src/tools/validity_state_checkers.js#L198
the string

     'Please lengthen this text to %l characters or more (you are currently using %l characters).'

will be printed. If you overload it, e.g.,

    hyperform.addTranslation("fr",{
      "Please lengthen this text to %l characters or more (you are currently using %l characters).": "Veuillez allonger ce texte pour atteindre %l caractères ou plus (vous avez écrit pour l'instant %l caractères)."
    };

it should work exactly as needed.

(Background: The translations in `localization.js` with fixed keys are based on key/message pairs in Firefox. Where Firefox had no support yet, I didn't introduce makeshift keys myself to save some bytes.)
