### ISSUE TITLE
Documentation incorrect regarding "hyperform.validityState"

### ISSUE THREAD

**Issue by mattkibbler** [hyperform/hyperform#75]
[This page](https://hyperform.js.org/docs/usage.html) of the documentation has this example:

```
if (hyperform.willValidate(form.elements[0])) {
  var is_valid = hyperform.validityState(form.elements[0]).valid;
}
```

However this function is actually exposed as `hyperform.ValidityState`, note the uppercase "V".

**Comment by Boldewyn** [comment]
Is fixed. Thanks a lot for noticing and telling me!
