### ISSUE TITLE
<form> novalidate is ignored - email field fires validation on blur

### ISSUE THREAD

**Issue by rbndm** [hyperform/hyperform#87]
In this example (https://codepen.io/anon/pen/KEvNdG?editors=1010) I am using ```<form novalidate>``` to disable browser default validation because I want to use Popper.js to show error messages. I wanted to use hyperform as a polyfill for older browsers.
The weird thing is, if I don't use hyperform (commenting line 6 in the example) it works as desired. But when I enable hyperform, if I enter an invalid email (e.g. "a") and I change focus to other field, the default validation message appears under the email field. I tested it on an older Firefox 63.0 32-bit and on Firefox mobile 65.0.1 

Is there anything wrong?

Thanks in advance

**Comment by Boldewyn** [comment]
Hi,

thank you for the report and test case! I’m really sorry for taking so long for a response!

Yes, that is indeed a bug. I.e., browsers keep completely silent, while Hyperform will still run the `revalidate` routines on `change`/`blur`.

I’ve fixed this in the upcoming 0.11 release, which I’ll publish in a moment. If you’re stuck with the old version, you can work around the problem with the `revalidate: 'never'` setting:

```
hyperform(form, {
  revalidate: 'never',
});
```
